//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_location
    {
        public int id { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> lon { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string status { get; set; }
        public Nullable<int> pid { get; set; }
    }
}
