//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_mabus
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string start_bus { get; set; }
        public string end_bus { get; set; }
        public string status { get; set; }
        public string time_stop { get; set; }
    }
}
