//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSAuthentication.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_cake
    {
        public int Id { get; set; }
        public Nullable<int> Id_pontbus { get; set; }
        public Nullable<int> Id_location { get; set; }
        public string status { get; set; }
    }
}
